[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter =
    +<atmega328p/>
    -<esp8266/>
    -<esp32_relay/>
    -<esp32_dht/>

[env:esp8266]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
build_src_filter =
    +<esp8266/>
    -<atmega328p/>
    -<esp32_relay/>
    -<esp32_dht/>

[env:esp32_relay]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<esp32_relay/>
    -<esp32_dht/>
    -<atmega328p/>
    -<esp8266/>

[env:esp32_dht]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_src_filter =
    +<esp32_dht/>
    -<esp32_relay/>
    -<atmega328p/>
    -<esp8266/>

; Same firmware as esp32_dht, different mDNS name. Add one of these per board.
[env:esp32_dht4]
extends = env:esp32_dht
build_flags = -DHOSTNAME_STR='"dht4"'

[env:esp32_dht3]
extends = env:esp32_dht
build_flags = -DHOSTNAME_STR='"dht3"' -DNO_SSR

[env:esp32_dht2]
extends = env:esp32_dht
build_flags = -DHOSTNAME_STR='"dht2"' -DNO_SSR
