[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
build_src_filter =
    +<atmega328p/>
    -<esp8266/>

[env:esp8266]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
build_src_filter =
    +<esp8266/>
    -<atmega328p/>